name: CI Pipeline

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: prediction
          POSTGRES_USER: prediction
          POSTGRES_PASSWORD: prediction
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Containers
        run: |
          docker compose -f docker-compose.prod.yml up --build -d
          sleep 15  # Даем время для инициализации сервисов

      - name: Run Tests with Coverage
        run: |
          docker compose exec web coverage run --source='applications' manage.py test applications/ --keepdb
          docker compose exec web coverage report

      - name: Stop and Clean up Docker Containers
        if: always()
        run: |
          docker compose down
