version: '3.8'


x-environment-defaults: &environment-defaults
  DB_NAME: "prediction"
  DB_USER: "prediction"
  DB_PASSWORD: "prediction"
  DB_HOST: "postgres-db"



services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 8000:8000
    networks:
      - prediction-network
    depends_on:
      - postgres-db
      # - redis
    environment:
      <<: *environment-defaults
    env_file:
      - .env
    restart: on-failure:5


  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prediction
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - prediction-network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - prediction-network

  celery:
    build:
      context: ./
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres-db
    networks:
      - prediction-network


  celery-beat:
    build:
      context: ./
    command: celery -A config beat --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - celery
      - redis
      - postgres-db
    networks:
      - prediction-network


  


volumes:
  pg_data:
  static_volume:

networks:
  prediction-network:
    driver: bridge

