version: '3.8'

x-environment-defaults: &environment-defaults
  DB_NAME: "prediction"
  DB_USER: "prediction"
  DB_PASSWORD: "prediction"
  DB_HOST: "postgres-db"


services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    networks:
      - prediction-network
    depends_on:
      - postgres-db
      # - redis
    environment:
      <<: *environment-defaults
    env_file:
      - .env
    restart: on-failure:5
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/swagger/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prediction
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - prediction-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - prediction-network

  celery:
    build:
      context: ./
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres-db
    networks:
      - prediction-network
    environment:
      <<: *environment-defaults

  celery-beat:
    build:
      context: ./
    command: celery -A prediction beat --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - celery
      - redis
      - postgres-db
    networks:
      - prediction-network
    environment:
      <<: *environment-defaults

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

    networks:
      - prediction-network
      

volumes:
  pg_data:
  static_volume:

networks:
  prediction-network:
    driver: bridge


