# Generated by Django 5.1.2 on 2024-10-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
