# Generated by Django 5.1.2 on 2024-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_tag_options_alter_post_tags_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="posts",
                to="product.tag",
                verbose_name="Тег",
            ),
        ),
    ]
