# Generated by Django 5.1.2 on 2024-10-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_rename_title_post_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.CharField(max_length=255, verbose_name="тема поста"),
        ),
    ]
