# Generated by Django 5.1.2 on 2024-10-22 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_post_body_alter_post_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Рейтинг"
            ),
        ),
    ]
