# Generated by Django 5.1.2 on 2024-10-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_post_body_alter_rating_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
