# Generated by Django 5.1.2 on 2024-10-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.SmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Рейтинг"
            ),
        ),
    ]
