# Generated by Django 5.1.2 on 2024-10-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liftlog",
            options={
                "verbose_name": "Лог поднятия поста",
                "verbose_name_plural": "Лог поднятия поста",
            },
        ),
        migrations.AlterModelOptions(
            name="postliftsettings",
            options={
                "verbose_name": "поднятие поста",
                "verbose_name_plural": "поднятие поста",
            },
        ),
        migrations.AlterField(
            model_name="postliftsettings",
            name="days_of_week",
            field=models.CharField(
                choices=[
                    ("monday", "monday"),
                    ("tuesday", "tuesday"),
                    ("wednesday", "wednesday"),
                    ("thursday", "thursday"),
                    ("friday", "friday"),
                    ("saturday", "saturday"),
                    ("sunday", "sunday"),
                ],
                max_length=50,
                verbose_name="дни недели",
            ),
        ),
        migrations.AlterField(
            model_name="postliftsettings",
            name="end_date",
            field=models.DateField(verbose_name="Дата конца"),
        ),
        migrations.AlterField(
            model_name="postliftsettings",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lift_settings",
                to="product.post",
                verbose_name="Пост",
            ),
        ),
        migrations.AlterField(
            model_name="postliftsettings",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="postliftsettings",
            name="time",
            field=models.TimeField(verbose_name="Время"),
        ),
    ]
