# Generated by Django 5.1.2 on 2024-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0014_alter_liftlog_options_alter_postliftsettings_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DaysOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_of_week",
                    models.CharField(max_length=50, verbose_name="дни недели"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="postliftsettings",
            name="days_of_week",
        ),
        migrations.AddField(
            model_name="postliftsettings",
            name="days_of_week",
            field=models.ManyToManyField(
                to="product.daysofweek", verbose_name="дни недели "
            ),
        ),
    ]
