# Generated by Django 5.1.2 on 2024-10-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0015_daysofweek_remove_postliftsettings_days_of_week_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="product.tag",
                verbose_name="Тег",
            ),
        ),
    ]
