# Generated by Django 5.1.2 on 2024-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
        migrations.AlterField(
            model_name="country",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Имя"
            ),
        ),
    ]
