# Generated by Django 5.1.2 on 2024-10-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="create_posts",
            field=models.BooleanField(default=True),
        ),
    ]
