# Generated by Django 5.1.2 on 2024-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_customuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Био"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="create_posts",
            field=models.BooleanField(
                default=True, verbose_name="Может ли создавать посты"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли доступ"
            ),
        ),
    ]
