# Generated by Django 5.1.2 on 2024-10-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0006_alter_customuser_bio_alter_customuser_create_posts_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(
                default=True, verbose_name="Есть ли доступ"
            ),
        ),
    ]
